name: Build Baka-MPlayer
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'

      - name: Create MPV Stub
        shell: pwsh
        run: |
          # Создаем папку в корне
          New-Item -ItemType Directory -Path "include/mpv" -Force
          $h = '#ifndef MPV_CLIENT_H_`n#define MPV_CLIENT_H_`ntypedef struct mpv_handle mpv_handle;`n#endif'
          $h | Out-File -FilePath "include/mpv/client.h" -Encoding UTF8
          "" | Out-File -FilePath "include/mpv/qthelper.hpp" -Encoding UTF8

      - name: Build project
        shell: pwsh
        run: |
          # Ищем файл .pro и заходим к нему
          $pro = Get-ChildItem -Filter "Baka-MPlayer.pro" -Recurse | Select-Object -First 1
          cd $pro.Directory.FullName
          
          # Запускаем сборку, насильно указывая путь к нашим заглушкам
          qmake Baka-MPlayer.pro "INCLUDEPATH+=../include" "CONFIG+=no_pkg_config"
          mingw32-make -j2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Baka-MPlayer-Build
          path: "**/release/*.exe"
