name: Build Baka-MPlayer
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'

      - name: Setup MPV (Headers + Libs)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "src/include/mpv" -Force
          $baseUrl = "https://raw.githubusercontent.com/mpv-player/mpv/master/libmpv"
          # Скачиваем заголовки (чертежи)
          Invoke-WebRequest -Uri "$baseUrl/client.h" -OutFile "src/include/mpv/client.h"
          Invoke-WebRequest -Uri "$baseUrl/qthelper.hpp" -OutFile "src/include/mpv/qthelper.hpp"
          Write-Host "Headers downloaded."

      - name: Build project
        shell: pwsh
        run: |
          if (Test-Path "src/Baka-MPlayer.pro") { cd src }
          qmake Baka-MPlayer.pro INCLUDEPATH+=include "CONFIG+=no_pkg_config"
          mingw32-make -j2

      - name: Prepare Artifacts
        shell: pwsh
        run: |
          # Создаем папку для готового плеера
          New-Item -ItemType Directory -Path "Dist" -Force
          Get-ChildItem -Path "**/release/*.exe" -Recurse | Copy-Item -Destination "Dist/"
          Write-Host "EXE moved to Dist folder"

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: Baka-MPlayer-Build
          path: Dist/
